// lib/mock-form-data.ts
import { FormDefinition } from "./types";

export const mockForm: FormDefinition = {
  id: "form_123",
  title: "Pesquisa de Satisfação do Cliente",
  description: "Por favor, preencha esta pesquisa para nos ajudar a melhorar nossos serviços.",
  blocks: [
    { id: "block1", title: "Informações Básicas", description: "Comece com seus dados." },
    { id: "block2", title: "Detalhes do Serviço", description: "Conte-nos sobre sua experiência." },
    { id: "block3", title: "Feedback Final", description: "Suas últimas considerações." },
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  questions: [
    {
      id: "q1",
      bloco_id: "block1",
      label: "Qual o seu nome completo?",
      type: "text_input",
      required: true,
      ordem_exibicao: 1,
      placeholder: "Seu nome aqui",
    },
    {
      id: "q2",
      bloco_id: "block1",
      label: "Qual o seu feedback geral sobre nosso serviço?",
      type: "textarea_input",
      required: false,
      ordem_exibicao: 2,
      placeholder: "Escreva seu feedback aqui...",
    },
    {
      id: "q3",
      bloco_id: "block1",
      label: "Com que frequência você utiliza nosso serviço?",
      type: "radio",
      required: true,
      ordem_exibicao: 3,
      options: [
        { value: "daily", label: "Diariamente" },
        { value: "weekly", label: "Semanalmente" },
        { value: "monthly", label: "Mensalmente" },
        { value: "rarely", label: "Raramente" },
      ],
    },
    {
      id: "q4",
      bloco_id: "block1",
      label: "Quais recursos você mais utiliza?",
      type: "caixa_selecao",
      required: false,
      ordem_exibicao: 4,
      options: [
        { value: "feature_a", label: "Recurso A" },
        { value: "feature_b", label: "Recurso B" },
        { value: "feature_c", label: "Recurso C" },
      ],
    },
    {
      id: "q5",
      bloco_id: "block2",
      label: "Selecione a data da sua última interação conosco:",
      type: "date_picker",
      required: true,
      ordem_exibicao: 5,
      placeholder: "DD/MM/YYYY", // Added placeholder
    },
    {
      id: "q6",
      bloco_id: "block2",
      label: "Quantos anos você tem?",
      type: "number_input",
      required: true,
      ordem_exibicao: 6,
      placeholder: "Sua idade",
    },
    {
      id: "q7",
      bloco_id: "block2",
      label: "Você recomendaria nosso serviço a um amigo?",
      type: "switch",
      required: true,
      ordem_exibicao: 7,
      defaultValue: false,
    },
    {
      id: "q8",
      bloco_id: "block2",
      label: "Em uma escala de 1 a 10, o quão satisfeito você está com nosso suporte?",
      type: "slider",
      required: true,
      ordem_exibicao: 8,
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 5,
    },
    {
      id: "q9",
      bloco_id: "block3",
      label: "Qual a probabilidade de você recomendar nossa empresa a um amigo ou colega?",
      type: "nps",
      required: true,
      ordem_exibicao: 9,
      min: 0,
      max: 10,
      minLabel: "Nada provável",
      maxLabel: "Extremamente provável",
    },
    {
      id: "q10",
      bloco_id: "block3",
      label: "Qual a sua área de atuação?",
      type: "select",
      required: true,
      ordem_exibicao: 10,
      options: [
        { value: "it", label: "Tecnologia da Informação" },
        { value: "finance", label: "Finanças" },
        { value: "health", label: "Saúde" },
        { value: "education", label: "Educação" },
        { value: "other", label: "Outra" },
      ],
    },
  ],
};
